### ISSUE TITLE
Exceptions are never thrown with context...

### ISSUE THREAD

**Issue by mw-root** [dahlke/terrasnek#13]
I appreciate that messages are displayed via logger, but the error itself has no message whatsoever. This means that catching these and transforming them with context is impossible.

```
        elif req.status_code == HTTP_NOT_FOUND:
            err = json.loads(req.content.decode("utf-8"))
            self._logger.error(err)
            raise TFCHTTPNotFound()
```

If you catch this exception there is no context.

I suggest at the very least to pass err as an argument to the exceptions.

**Comment by dahlke** [comment]
Closing as I will focus on Issue #14 to resolve this. Thanks for reporting, will update here shortly.
