### ISSUE TITLE
Support for 429 API rate limiting exception handling

### ISSUE THREAD

**Issue by paullschock** [dahlke/terrasnek#18]
Hey! Love the utility, been using it happily...

I have a very large TFE org  in terms of workspaces (several hundred+) to maintain and we've been the hammering the API. While I can increase it on our private instance, it would be not ideal for us when using cloud. (https://www.terraform.io/docs/cloud/api/index.html#rate-limiting)

Right now, I am catching these parsing TFCHTTPUnclassified, but looking at the other known HTTP response type handling, having a specific exception for this this would allow me to more easily catch and sleep when hitting the limit. 

Proposing something like this: https://github.com/paullschock/terrasnek/commit/dbba341ec78c46d65466466312e8df9578424c4b 

Happy to make a PR with commit, but wanted to check with issue first.

**Comment by dahlke** [comment]
Hey Paul,

I'm comfortable with this. Peeked at your commit. If you want me to merge that into the main project, feel free to submit a PR. Once you have the PR submitted, I'll close this out and merge it.

Thanks for using `terrasnek`, btw.

Cheers.

**Comment by paullschock** [comment]
PR is up. I didn't get a chance to run this through CircleCI as I don't access to my test tfe modules over the weekend. Can run through a build if that's helpful. Docs don't include exceptions, so I haven't added anything there. Thanks for the quick answer!

**Comment by dahlke** [comment]
Yep, I'll take care of that for you. Thanks again.

**Comment by dahlke** [comment]
I merged your PR into the 0.1.1 branch and it didn't break any tests. 😄  Will finish a couple things and release soon.
