### ISSUE TITLE
Handle non-json error responses

### ISSUE THREAD

**Issue by jimrthy** [dahlke/terrasnek#23]
I'm trying to list terraform states, and I'm getting back a 504 response: gateway timeout.

The _get method in endpoint.py falls through to its final else clause, where it should raise a TFCHTTPUnclassified exception.

But it fails before that when it tries to parse the json in the response, because whatever front-end we're using returned a message in HTML.

So all I see in the logs is a json.decoder.JSONDecodeError "Expecting value: line 1 column 1 (char 0)" error.

It would be helpful to catch that exception and do something like log the raw req.content, and possibly the status code (I couldn't tell what was failing until I stepped through it with a debugger).

I can submit a merge request, if that would be helpful. Honestly, this seems like something that should apply to all the end-points.

**Comment by dahlke** [comment]
This seems reasonable to me @jimrthy. Feel free to open up a merge request, otherwise I'll get to it some time later this week.

**Comment by jimrthy** [comment]
https://github.com/dahlke/terrasnek/pull/24

**Comment by dahlke** [comment]
Merged.

**Comment by jimrthy** [comment]
Wow, that was fast. Thanks!
