### ISSUE TITLE
str include param get exploded by join

### ISSUE THREAD

**Issue by mw-root** [dahlke/terrasnek#26]
It would be nice to be able to send a single string for includes

Trying tf.teams.list(include='users')  will turn 'users' into [ 'u', 's', 'e', 'r', 's'] and join that into a path query.

https://github.com/dahlke/terrasnek/blob/master/terrasnek/endpoint.py

[        if include is not None:
            joined_include = ",".join(include)
            q_options.append(f"include={joined_include}")](https://github.com/dahlke/terrasnek/blob/master/terrasnek/endpoint.py#:~:text=if%20include%20is,f%22include%3D%7Bjoined_include%7D%22))

**Comment by dahlke** [comment]
Great feedback. Before I accept your PR, I'd like your opinion. Is it better to support strings **and** lists for this parameter? Or force lists (my preference) and document it better?

**Comment by mw-root** [comment]
Good point, maybe it's best to stick with a list but type check the input parameter and throw an exception if it isn't a list.

The behaviour of python treating a string as an iterable is somewhat annoying IMO. Not that it matters much here.. a tuple of a single string will do the same thing.

**Comment by dahlke** [comment]
Sounds good. I'm going to force lists, and add some documentation, then I'll close this and deny the PR. Thanks for the feedback again!

**Comment by dahlke** [comment]
I added this functionality to the 0.1.8 branch and added some documentation for it. Closing this and the PR out.
