### ISSUE TITLE
Workspaces List of API endpoint support filters

### ISSUE THREAD

**Issue by twink0r** [dahlke/terrasnek#32]
Hi!

I checked the List endpoint of the Workspaces API, and it supports filter. The documentation didn't list the feature, but the following request shows the feature support of using filters.

`https://app.terraform.io/api/v2/organizations/xxx/workspaces?fields[workspace][]=current_run&fields[workspace][]=latest_change_at&fields[workspace][]=name&fields[workspace][]=vcs_repo_identifier&fields[workspace][]=locked&fields[workspace][]=tag_names&fields[workspace][]=assessments_enabled&fields[workspace][]=current_assessment_result&fields[workspace][]=permissions&fields[workspace][]=execution_mode&fields[workspace][]=organization&fields[run][]=status&fields[assessment-result][]=drifted&fields[assessment-result][]=succeeded&fields[assessment-result][]=all_checks_succeeded&filter[current-run][status]=errored&include=current_run,current_assessment_result,organization&organization_name=xxx&page[number]=1&page[size]=20&search[name]=dns-&sort=name
`

I tried this locally, and it works fine with a simple patch, but I'm not familiar with python tests.

```
    def list(self, page=None, page_size=None, include=None, search=None, filters=None):
        """
        ``GET /organizations/:organization_name/workspaces``

        `Workspaces List API Doc Reference \
            <https://www.terraform.io/docs/cloud/api/workspaces.html#list-workspaces>`_

        `Query Parameter(s) Details \
            <https://www.terraform.io/docs/cloud/api/workspaces.html#query-parameters>`__
        """
        return self._list(self._org_api_v2_base_url, \
            page=page, page_size=page_size, include=include, search=search, filters=filters)
```

**Comment by dahlke** [comment]
Makes sense. I just made a change and pushed it. Will update the docs when I push a new version.

**Comment by twink0r** [comment]
Hi @dahlke,

I would suggest adding this to list_all() as well.
