### ISSUE TITLE
PEP8 and related formatting issues

### ISSUE THREAD

**Issue by evilensky** [dahlke/terrasnek#40]
IDEs such as Jetbrains Pycharm and VS Code flag numerous formatting violations in various places. The usual gubbins like trailing white space, inconsistent use of line continuation markers, and lack of trailing white space on end of file.

A possible solution would be to reformat the code base in [black](https://pypi.org/project/black/) providing a consistent, uncompromising style.  Black has the distinct benefit of absolving projects of any current or future formatting discussions. But some of its choices are controversial.

Possible acceptance criteria would be: code base is reformatted / PEP8 errors are all resolved and a CI step is added to enforce formatting /  prevent formatting regressions.

**Comment by dahlke** [comment]
Given that there is a low number of contributors to this project at this time, I'm going to stick with the current linting pattern. If this grows and there are more contributors, then I'd be happy to defer to a larger group of maintainers.
