### ISSUE TITLE
When will a new release come out with filters functionality for teams and workspaces?

### ISSUE THREAD

**Issue by frielp** [dahlke/terrasnek#43]
Do you know when you plan to release a new version of terrasnek on PyPy? We have some python code that uses the `teams.list_all` which currently takes ~65 seconds to return and `workspaces.list_all` which currently takes ~90 seconds to return because we can't include a filter in the API call with the 0.1.10 release.

I would like to use `filters` that was added to [teams.py](https://github.com/dahlke/terrasnek/blob/main/terrasnek/teams.py) in https://github.com/dahlke/terrasnek/commit/d6b8a9c4e5a8f388a7864a6d544faaa630cdb6d5 and [workspaces.py](https://github.com/dahlke/terrasnek/blob/main/terrasnek/workspaces.py) in https://github.com/dahlke/terrasnek/commit/9d6bd20ebdb527d0c26e08f039a67e50512fdb9f but those changes have not been released yet.

Thanks!
Paul

**Comment by dahlke** [comment]
Planning to release a new version this week.

**Comment by frielp** [comment]
Great to hear, thank you!

**Comment by dahlke** [comment]
I have released [v0.1.11](https://github.com/dahlke/terrasnek/releases/tag/0.1.11). Let me know if you have any issues. Happy holidays.

**Comment by frielp** [comment]
@dahlke Thanks very much for this, I verified we are able to use some of these new features 👍
