### ISSUE TITLE
Check version method break library in air-gaped environments

### ISSUE THREAD

**Issue by miguelcubillo** [dahlke/terrasnek#45]
https://github.com/dahlke/terrasnek/blob/0807ca819504d0e243774a8c42ffca1374aa5dc9/terrasnek/api.py#L258

When using the library a lambda without connectivity to pypi the constructor of the api object cant be invoked and fails with the following error:

[ERROR] ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/terrasnek/json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out')) Traceback (most recent
 call last):   File "/var/task/example_lambda.py", line 423, in lambda_handler     tfe_api = terrasnek.api.TFC(   File "/var/task/terrasnek/api.py", line 236, in __init__     self._check_version()   File "/var/task/terrasnek/api.py",
 line 257, in _check_version     r = requests.get(f'[https://pypi.org/pypi/{self.package_name}/json')](https://pypi.org/pypi/%7Bself.package_name%7D/json%27))
   File "/var/task/requests/api.py", line 73, in get     return request("get", url, params=params, **kwargs)   File "/var/task/requests/api.py", line 59, in request     return session.request(method=method, url=url, **kwargs)   File "/var/task/requests/sessions.py",
 line 587, in request     resp = self.send(prep, **send_kwargs)   File "/var/task/requests/sessions.py", line 701, in send     r = adapter.send(request, **kwargs)   File "/var/task/requests/adapters.py", line 565, in send     raise ConnectionError(e, request=request)

Would it be possible to make this check non blocking?

Regards,
Miguel

**Comment by dahlke** [comment]
Makes sense, I can add a flag to allow for no checking.
