### ISSUE TITLE
api.vars error | SOLVED with api.variables

### ISSUE THREAD

**Issue by WernerWildenboer** [dahlke/terrasnek#5]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

When running 
`api.vars`
The following error is returned 
`AttributeError: 'TFC' object has no attribute 'vars'`

After a deep dive into the `api.py` file I found `variables `
The following code might be funky `endpoint replace`

The following is working fine for me, but this should be corrected or a new convention should be chosen 
` api.variables.create(create_variable_payload)`

**Comment by dahlke** [comment]
Thanks for filing this @WernerWildenboer. I updated the documentation before releasing v0.0.5. I believe this should be sorted out now, but feel free to re-open this if this is not the case.
