### ISSUE TITLE
Search in workspace list_all function is not working for version >=0.1.11

### ISSUE THREAD

**Issue by manojwajekar** [dahlke/terrasnek#52]
Hello,

The search in workspace list_all function is not working for version >=0.1.11; it ignores the search filter and always returns all workspaces within the organization. Search is working as excepted for version 0.1.10
https://terrasnek.readthedocs.io/en/latest/workspaces.html#terrasnek.workspaces.TFCWorkspaces.list_all

python version: 3.7.5

````
from terrasnek.api import TFC

TFC_TOKEN="<Token>"
tfc_api = TFC(TFC_TOKEN, "https://app.terraform.io", verify=False)
tfc_api.set_org("<organization>")

all_ws = tfc_api.workspaces.list_all(search='test')["data"]

print(all_ws)
````

Thanks.

**Comment by dahlke** [comment]
Many more search options had support added, so you need to pass a dict in, specifying what you are searching. The code that handles it is [here](https://github.com/dahlke/terrasnek/blob/011e108c728b59343a865b6d42efe2b6a25c2ff4/terrasnek/endpoint.py#L141-L155), and there is an example in the test [here](https://github.com/dahlke/terrasnek/blob/011e108c728b59343a865b6d42efe2b6a25c2ff4/test/workspaces_test.py#L40-L43). Closing this, but can reopen if I'm missing something.
