### ISSUE TITLE
Payload to assign varsets to workspaces and projects is wrong

### ISSUE THREAD

**Issue by burcukinay** [dahlke/terrasnek#53]
When I tried to use these endpoints I see that it returns success but the assignment is never made. After debugging I found out the payload that terrasnek uses is:
`"<workspace-id>"`
or
`"<project-id>"`

Expected payload, verified using Postman:
```
{
  "data": [
    {
      "type": "workspaces",
      "id": "<workspace-id>"
    }
  ]
}
```
or 
```
{
  "data": [
    {
      "type": "projects",
      "id": "<project-id>"
    }
  ]
}
```
You can see this in the documentation: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/variable-sets#apply-variable-set-to-workspaces
and
https://developer.hashicorp.com/terraform/cloud-docs/api-docs/variable-sets#apply-variable-set-to-projects

If you use the current payload it fails silently returning 204, but it is a no-op.

**Comment by dahlke** [comment]
Can you point out where I build the payload for you? In most every case I just link out to the official docs and rely on the user to build the payload.

**Comment by dahlke** [comment]
I'm going to close this one out in the meantime as I can't find anything in the code where I build the payload on behalf of the user. It's a bit of a rough edge, but it allows for the payloads to be more dynamic without having to keep up with every little update in the acceptable payload structure.
