### ISSUE TITLE
Linter and auto-completion with Terranesk

### ISSUE THREAD

**Issue by mcandries** [dahlke/terrasnek#6]
Hello and thanks for Terrasnek !

It seem's that the dynamic attributes adding into the TFC super class make things harder for linter and auto-completion.
I got a lot of 'Instance of 'TFC' has no 'XXX' member', and autocompletion into IDE doesn't work too.

Will you be OK to replace the dynamic attributes adding by a less smart but more user friendly static attributes adding ? If so I can make a PR in this way.

Have a nice day !

**Comment by dahlke** [comment]
Thanks for reporting this. I actually had it set up this way in the past. If it makes your and other's lives easier, I'm happy to go back to doing it that way. Feel free to put together a PR and I'll take a look.

**Comment by dahlke** [comment]
I resolved this issue in v0.0.9. Looks to work for me, let me know if you have any issues.

**Comment by mcandries** [comment]
Hi !

Thanks, it work great for autocompletion in VSCODE, at least for the "1st level" (example if I type my_TFC. the autocompletion help me with all the possiblities) ! 

But from the "2nd level" it didn't work, example if I type my_TFC.runs. autocompletion don't help me because the linter think "runs" is a None type. So autocompletion don't understand more about function parameters too.

I will make a PR that add typing, i you wish to include it.
