### ISSUE TITLE
How to catch error from _post method ?

### ISSUE THREAD

**Issue by mcandries** [dahlke/terrasnek#7]
Hello,

Some functions like "runs.apply" use the "_post" function of TFCEndpoint.

When an error occur during the post (like a bad HTTP response code), the error is logged, but nothing is returned, nor exception raised by the _post function. 

So, is there a way for the main calling function to know that something goes wrong during the terrasnek function ? (in the two case the function only return 'None')

Example : If i do a terrasnek "apply.run" function call, how do i know if the call was a success or a fail ?

Thanks !

**Comment by dahlke** [comment]
Yep, for ease of development early on I just swallowed the exceptions and logged them. I intend to surface them in the future, so will leave this open until I do.

**Comment by dahlke** [comment]
This has been addressed in the `v0.0.10` branch, which I will release next week.
